#!/bin/bash

if [ $# -ne 2 ] ; then
	echo "Usage: customize_shared <dir> <name>"
	exit 1
fi

INDIR="`dirname \"$0\"`"
OUTDIR="$1"
NAME="$2"
NAME_UCASE="`echo \"$NAME\" | tr '[:lower:]' '[:upper:]'`"

#~ for f in errors.h api.h ; do
	#~ sed "s/SHARED/$NAME_UCASE/g;s/shared/$NAME/g" "$INDIR/src/$f" > "$OUTDIR/src/${NAME}_$f"
#~ done

[ -d "$OUTDIR/doc" ] || mkdir "$OUTDIR/doc"
sed "s/<NAME>/libt3$NAME/g" "$INDIR/doc/doxygen.conf" > "$OUTDIR/doc/doxygen.conf"
cp "$INDIR/doc/DoxygenLayout.xml" "$OUTDIR/doc/DoxygenLayout.xml"
