#!/bin/bash

cd `dirname "$0"`/..
for i in makesys shared key unicode window widget config highlight edit ; do
	[ -d "$i" ] || continue
	echo "==== Executing $@ for $i ===="
	( cd "$i" ; "$@" )
done

