#!/bin/bash

cd "$(dirname "$0")"
URL=$(git config remote.origin.url)
URL=${URL%/*}

cd ..
for i in tilde t3key t3window t3widget t3config t3highlight makesys ; do
	[ -d "$i" ] && continue
	echo "Cloning $URL/$i.git"
	git clone "$URL/$i.git"
done
